version: '3'

services:
  db:
    image: cantarino/mysql
    environment:
      MYSQL_DATABASE: gacoss
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user12345
    ports:
      - "3306:3306"
  web:
    image: cantarino/php7
    container_name: php7
    depends_on:
      - db
    volumes:
        - /Applications/MAMP/htdocs/gacoss/public/:/var/www/html/
    ports:
      - "80:80"
    environment: 
        WEB_DOCUMENT_ROOT: public 
    stdin_open: true
    tty: true
    