version: "3.2"
services:
  php:
    image: cantarino/php7
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - /Applications/MAMP/htdocs/gacoss/:/var/www/html/
  mysql:
    image: cantarino/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: user12345
        MYSQL_DATABASE: gacoss
    networks:
#        - frontend
        backend:
            aliases:
                - mysql
    ports:
#        - "3306:3306"
        - "3306:33060"
networks:
  frontend:
  backend: